
name: Build dist/index.js

on:
  push:
    branches: [ main-none ]
  pull_request:
    branches: [ main-none ]

jobs:            
  build-dist:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'

    steps:
      - name: Checkout ğŸ›ï¸
        uses: actions/checkout@v2
        
      - name: Validate dist/index.js is built
        run: |
          npm install
          sudo npm i -g @vercel/ncc
          ncc build index.js -o ./dist/ci_compiled.js
          if cmp -s "dist/ci_compiled/index.js" "dist/index.js"; then echo ""; else echo "You need to compile index.js 'ncc build index.js'" && exit 1; fi
        
