
name: Build dist/index.js

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:            
  build-dist:
    runs-on: ${{ matrix.os }}
    if: github.event_name == 'pull_request'
    strategy:
      matrix:
        os: [ubuntu-latest]
        platform: [x64]
        compiler: [node]

    steps:
      - name: Checkout ğŸ›ï¸
        uses: actions/checkout@v2
        
      - name: Download NPM Dependencies and Build ğŸ”§
        run: |
          npm install
          sudo npm i -g @vercel/ncc
          npm run build
          if [ "dist/index.js" -nt "index.js" ]; then exit 0; else echo "You need to compile index.js 'ncc build index.js'"; exit 1; fi
        
